---
- name: Create users on all servers
  hosts: dbserver
  tasks:
    - name: Create users
      user:
        name: admin
        password: admin
        home: /tmp/admin
        uid: 9090
        shell: /bin/bash
        comment: "A normal user"

...
