---
- name: Install jenkins and required s/w's
  hosts: 172.31.47.148
  tasks:
    - name: Install jdk
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: Install git
      apt:
        name: git
        state: present
    - name: Install maven
      apt:
        name: maven
        state: present
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.452.1/jenkins.war
        dest: /home/ubuntu


...
